// Homeowner guides — informational articles that support the service + location pages.
// Keep these general and accurate: rules vary by jurisdiction, so every guide tells readers
// to confirm specifics with their own building department. `body` is an array of
// [tag, html] blocks so the build can render headings, paragraphs and lists.

module.exports = [
  {
    slug: 'impact-rated-windows-vs-hurricane-shutters',
    short: 'Impact-rated windows vs. shutters',
    quoteH2: 'Ready to Make Your Home Hurricane-Proof?',
    moreH2: 'More on Building for Florida Weather',
    title: 'Impact-Rated Windows vs. Hurricane Shutters | Brunderman',
    description: 'Impact-rated windows or hurricane shutters? What Florida code requires, how each protects a home, insurance and energy effects, and what a builder recommends.',
    h1: 'Impact-Rated Windows vs. Hurricane Shutters: What Southwest Florida Homes Need',
    lead: 'Every home in our region has to protect its openings from wind-borne debris. Here is how impact-rated windows and shutters compare, and why we put impact glass in every home we build.',
    card: 'Code requirements, protection, insurance, energy, and daily living — compared by a builder.',
    body: [
      ['p', 'Port Charlotte, Punta Gorda, North Port, Venice, and the rest of our service area sit inside the Florida Building Code\'s wind-borne debris region. In practical terms, that means every exterior opening on a new home, and every window or door you replace on an existing one, must either be impact-rated or be protected by an approved shutter system. The code gives you the choice. After four decades of building here, we have a clear preference.'],
      ['h2', 'How Each One Works'],
      ['p', '<strong>Impact-rated windows and doors</strong> use laminated glass, a tough plastic interlayer bonded between two panes, set in a reinforced frame and anchored to the structure. Tested products are hit with a 9-pound 2×4 fired from a cannon, then cycled through thousands of positive and negative pressure changes. The glass may crack, but it stays in the frame, and the building stays sealed.'],
      ['p', '<strong>Hurricane shutters</strong> protect ordinary glass by covering it. Options range from inexpensive steel or aluminum panels that bolt on before a storm, to accordion and roll-down shutters that stay mounted year-round, to fabric screens. All approved products pass the same impact tests; the difference is that they only protect the house when someone deploys them.'],
      ['h2', 'Where Shutters Fall Short'],
      ['ul', ['They have to be put up. Panel shutters mean a ladder, a drill, and hours of work in the days before landfall, often for an older homeowner or a seasonal resident who is not even in Florida.', 'A home with shutters up is dark and hard to leave. A home with impact glass is a normal house during the storm.', 'Panels need storage and get lost or damaged. Roll-down and accordion units add cost, maintenance, and something to look at on every window.', 'Ordinary glass behind a shutter gives none of the everyday benefits below.']],
      ['h2', 'What Impact-Rated Windows Give You Every Day'],
      ['ul', ['<strong>Noise.</strong> Laminated glass noticeably cuts road, lawn, and neighbor noise.', '<strong>Energy.</strong> Most impact units are low-E, insulated glass, so the house holds its cool air better than the single-pane aluminum windows in a 1980s home.', '<strong>UV.</strong> The interlayer blocks most ultraviolet light, which slows fading of floors and furniture.', '<strong>Security.</strong> The same glass that stops a 2×4 stops a burglar\'s pry bar.', '<strong>Insurance.</strong> Opening protection is one of the features Florida wind-mitigation inspections credit, and impact glass qualifies without any action on your part each season.']],
      ['h2', 'Cost and Trade-Offs'],
      ['p', 'Impact-rated windows cost more up front than standard windows plus panel shutters. The gap narrows against accordion or roll-down shutters and disappears when you count energy savings, insurance credits, and the labor of shuttering a house year after year. On a new custom home, the incremental cost of specifying impact glass from the start is modest relative to the total, which is why it is standard on every home we build.'],
      ['p', 'One honest caveat: impact glass is not a substitute for the rest of the structure. A hurricane-proof home is a system: concrete block or properly strapped walls, a roof tied to the foundation with a continuous load path, a wind-rated garage door, and a floor above the flood line. Protected openings keep the pressure out so that system can do its job.'],
      ['h2', 'Our Recommendation'],
      ['p', 'For new construction: impact-rated windows and doors on every opening, no exceptions. For an existing home, replacing the windows with impact-rated units is the single most valuable storm upgrade available, and the one we schedule first on a <a href="/services/home-remodeling.html">whole-home remodel</a>. If the budget only allows some openings now, start with the large sliders and the windows facing the most exposed direction, and protect the rest with shutters until they can be replaced.'],
      ['p', 'This is the standard behind our motto, <em>houses shouldn\'t break</em>. If you are planning a <a href="/services/custom-home-construction.html">custom home</a> or hardening the one you own, <a href="/about.html#quote">tell us about the project</a> and we will walk through the options.'],
      ['note', 'General information only. Product approvals, insurance credits, and code details change; confirm current requirements with your building department and insurer.'],
    ],
    related: [['/services/custom-home-construction.html', 'Hurricane-proof custom home construction'], ['/services/home-remodeling.html', 'Home remodeling and impact window replacement'], ['/locations/port-charlotte.html', 'General contractor in Port Charlotte']],
  },
  {
    slug: 'fema-50-percent-rule-charlotte-county',
    short: 'The FEMA 50% rule explained',
    quoteH2: 'Planning a Remodel in a Flood Zone? Talk to a Builder',
    moreH2: 'More on Flood Zones and Remodeling',
    title: 'FEMA 50% Rule Explained for SW Florida Homeowners | Brunderman',
    description: 'What the FEMA 50% rule means for remodeling a home in a flood zone in Port Charlotte, Punta Gorda, Englewood or North Port — and how to plan around it.',
    h1: 'The FEMA 50% Rule, Explained for Southwest Florida Homeowners',
    lead: 'If your home sits in a flood zone, one federal rule can decide how much remodeling you are allowed to do. Here is how the FEMA 50% rule works and how to plan a project around it.',
    card: 'How the substantial-improvement rule limits remodeling in flood zones — and how to plan around it.',
    body: [
      ['p', 'Homeowners across Charlotte County learned about the FEMA 50% rule the hard way after Hurricane Ian. The rule, explained simply, is not new, and it is not unique to Florida, but it matters more here than almost anywhere: a large share of the homes in Port Charlotte, Punta Gorda, Englewood, and Harbour Heights were built at ground level decades ago, in areas that today\'s flood maps place inside a special flood hazard area.'],
      ['h2', 'What the 50% Rule Says'],
      ['p', 'Communities that participate in the National Flood Insurance Program must enforce a "substantial improvement / substantial damage" standard. In plain terms: if a building in a special flood hazard area is improved, or repaired after damage, and the cost of that work equals or exceeds 50% of the market value of the structure, the whole building must be brought into compliance with current floodplain rules. For most older homes, compliance means the lowest floor has to be at or above the required flood elevation — which usually means elevating the house or replacing it.'],
      ['p', 'Two details trip people up. First, the 50% is measured against the value of the <strong>structure only</strong>, not the land. On a waterfront lot, the land is often worth far more than the house, so the threshold can be surprisingly low. Second, the rule applies to homes that are below the required elevation. A house that already meets current elevation requirements is not limited in the same way.'],
      ['h2', 'What Counts Toward the 50%'],
      ['p', 'Broadly, the cost of the work includes materials and labor for structural elements, interior finishes, and built-in systems. Local floodplain administrators publish their own worksheets, but these are commonly counted:'],
      ['ul', ['Demolition, framing, drywall, insulation, and flooring', 'Cabinets, countertops, and built-in appliances', 'Electrical, plumbing, and HVAC work', 'Windows, doors, roofing, and exterior finishes', 'Contractor overhead and profit, and the fair value of donated or owner labor']],
      ['p', 'Items that are commonly excluded include plans and permit fees, debris removal, landscaping, detached structures, and work outside the building footprint such as docks, seawalls, and pools. Always confirm with your own jurisdiction — the lists are similar but not identical.'],
      ['h2', 'How the Structure\'s Value Is Determined'],
      ['p', 'Most jurisdictions start with the building value from the county property appraiser, often with an adjustment factor. Owners are generally allowed to submit a private appraisal from a licensed appraiser instead, and doing so can make a meaningful difference when the appraiser\'s depreciated structure value comes in higher than the tax roll number.'],
      ['h2', 'Does Every Jurisdiction Apply It the Same Way?'],
      ['p', 'No. Unincorporated Charlotte County, the City of Punta Gorda, Sarasota County, the City of North Port, and the City of Venice each administer their own floodplain ordinance. Some look at each permit on its own; others add up improvements over a multi-year "lookback" period, so a kitchen this year and a bathroom next year may be counted together. Lookback periods and procedures have changed over time, so check the current rule before you plan a phased remodel.'],
      ['h2', 'Planning a Remodel Around the Rule'],
      ['ul', ['<strong>Find out where you stand first.</strong> Look up your flood zone and base flood elevation, and get an elevation certificate if you do not have one.', '<strong>Establish the structure value early.</strong> If the tax roll value looks low, an appraisal before design begins can widen your budget.', '<strong>Scope to the number.</strong> A good contractor can prioritize: fix the layout and the kitchen now, leave cosmetic items that do not require permits for later.', '<strong>Keep documentation.</strong> Itemized contracts make the jurisdiction\'s review faster and cleaner.', '<strong>Compare against rebuilding.</strong> When the wish list is far past the threshold, elevating or building new to current code may be the better long-term investment.']],
      ['p', 'Brunderman Building Co Inc has worked in these flood zones for four decades. When we look at a <a href="/services/home-remodeling.html">home remodeling</a> project or a <a href="/services/home-additions.html">home addition</a> near the water, the 50% question is part of the first conversation — before anyone spends money on drawings. If the answer points toward starting over, we are also a <a href="/services/custom-home-construction.html">custom home builder</a> and can price that path too.'],
      ['note', 'This guide is general information, not legal or regulatory advice. Floodplain rules are set and interpreted by your local building department; confirm the current requirements for your address before making decisions.'],
    ],
    related: [['/locations/punta-gorda.html', 'Building and remodeling in Punta Gorda'], ['/locations/charlotte-county.html', 'Building and remodeling in Charlotte County'], ['/locations/port-charlotte.html', 'General contractor in Port Charlotte']],
  },

  {
    slug: 'building-on-your-lot-port-charlotte-north-port',
    short: 'Building on your own lot',
    quoteH2: 'Have a Lot? Get It Evaluated Before You Design',
    moreH2: 'More on Building a Custom Home',
    title: 'Building on Your Lot in Port Charlotte & North Port | Brunderman',
    description: 'Own a vacant lot in Port Charlotte or North Port? What to check before you build — flood zone, fill, well and septic, scrub-jays, utilities and setbacks.',
    h1: 'Building on Your Own Lot in Port Charlotte or North Port: What to Check First',
    lead: 'Tens of thousands of platted lots in Port Charlotte and North Port are still vacant. Before you design a house for one, these are the things that determine what it will really cost to build there.',
    card: 'Flood zone, fill, well and septic, protected species, utilities — the lot checklist before you design.',
    body: [
      ['p', 'Port Charlotte and North Port were both laid out by General Development Corporation beginning in the 1950s: mile after mile of streets and canals, divided into lots of roughly 80 by 125 feet, most of which sat empty for decades. Many are owned by people who bought them long ago or inherited them. If that is you, the first thing to understand is that the lot may be the least expensive part of your future home — but it is also the part with the most unknowns. Two lots on the same street can differ by tens of thousands of dollars in site costs.'],
      ['h2', '1. Flood Zone and Required Floor Elevation'],
      ['p', 'Look up the lot on the FEMA flood map or your county\'s GIS site. If it is in a special flood hazard area, the map gives a base flood elevation, and local rules typically require the finished floor to sit above it by a set margin. The difference between the existing ground and the required floor height tells you how much fill, stem wall, or elevated construction the house will need.'],
      ['h2', '2. Fill and Drainage'],
      ['p', 'Even outside a flood zone, most lots need fill to raise the building pad above the road and direct water to the swales. Low or wet lots need more. Fill dirt, compaction, and grading are real line items, and they have to be placed without pushing stormwater onto the neighbors.'],
      ['h2', '3. Water and Sewer — or Well and Septic'],
      ['p', 'Utility service is block by block. Some areas have central water and sewer, some have water only, and many — especially in North Port — have neither. Without utilities you will need a drilled well with treatment equipment and a permitted septic system. The septic design depends on soil and the seasonal high water table, and the tank and drain field occupy a meaningful part of the lot, which affects where the house, driveway, and a future pool can go.'],
      ['h2', '4. Protected Species'],
      ['p', 'Two protected animals come up constantly here. Gopher tortoise burrows must be surveyed for, and any tortoises relocated under a state permit before clearing. Parts of Charlotte County and North Port are also mapped Florida scrub-jay habitat, where building may involve a review and a mitigation fee. Neither is a deal-breaker, but both take time, so check early.'],
      ['h2', '5. Setbacks, Easements, and Deed Restrictions'],
      ['p', 'A current survey shows the lot lines, easements, and any encroachments. Zoning sets the front, side, and rear setbacks; canal lots have additional setbacks from the water. Some subdivisions carry deed restrictions on minimum home size or exterior materials. Together these define the buildable envelope — know it before you fall in love with a floor plan.'],
      ['h2', '6. Canal Lots: Seawalls and Access'],
      ['p', 'On a saltwater canal, find out the condition of the seawall and whether the route to open water passes under fixed bridges. A failing seawall is a major expense best handled before the house is built, while equipment can still reach it.'],
      ['h2', '7. Impact Fees and Permit Costs'],
      ['p', 'Charlotte County and the City of North Port both charge impact fees on new homes, in addition to permit fees. They change periodically, so ask your builder for current figures and make sure they are in the budget rather than a surprise at permit pickup.'],
      ['h2', 'Put It All in One Number'],
      ['p', 'A quote for "the house" is only useful when it includes the ground it stands on. When we evaluate a lot for <a href="/services/custom-home-construction.html">custom home construction</a>, we price clearing, fill, well and septic or utility connections, culvert and driveway, and fees alongside the home itself, so the total reflects that specific lot. More than 200 of the homes we have built are in Charlotte County, most on lots exactly like these. Read more about building in <a href="/locations/port-charlotte.html">Port Charlotte</a> and <a href="/locations/north-port.html">North Port</a>, or <a href="/about.html#quote">tell us about your lot</a>.'],
      ['note', 'General information only. Flood maps, utility availability, fees, and environmental rules change; verify the details for your parcel with the county or city before you buy or design.'],
    ],
    related: [['/locations/north-port.html', 'Home builder in North Port'], ['/locations/port-charlotte.html', 'General contractor in Port Charlotte'], ['/services/custom-home-construction.html', 'Custom home construction']],
  },

  {
    slug: 'remodeling-permits-southwest-florida',
    short: 'Which projects need a permit',
    quoteH2: 'Want a Remodel Done Right, Permits Included?',
    moreH2: 'More on Remodeling in Southwest Florida',
    title: 'Do I Need a Permit to Remodel in SW Florida? | Brunderman',
    description: 'Which kitchen, bathroom and home remodeling projects need a building permit in Southwest Florida, which usually do not, and why permits protect homeowners.',
    h1: 'Which Remodeling Projects Need a Permit in Southwest Florida?',
    lead: 'Paint does not. A new shower valve probably does. Here is a practical guide to when a kitchen, bathroom, or whole-home remodel needs a building permit — and why skipping one is a bad bargain.',
    card: 'When kitchen, bath, and whole-home projects need a permit, and why it protects you.',
    body: [
      ['p', 'Florida has a single statewide building code, but permits are issued locally — by Charlotte County or Sarasota County, or by cities such as Punta Gorda, North Port, and Venice. The details differ a little from one counter to the next, yet the basic principle is the same everywhere: work that affects structure, life safety, or the building\'s systems needs a permit; purely cosmetic work generally does not.'],
      ['h2', 'Work That Generally Needs a Permit'],
      ['ul', ['Removing, moving, or adding walls — especially anything load-bearing', 'New or relocated plumbing: moving a sink, converting a tub to a shower, adding a bathroom', 'New circuits, panel upgrades, and most electrical work beyond like-for-like device replacement', 'HVAC replacement or new ductwork', 'Window and exterior door replacement (products must meet wind-load and, in our region, impact or shutter requirements)', 'Re-roofing and structural roof repairs', 'Room additions, lanai enclosures, and garage conversions', 'Water heater replacement in most jurisdictions']],
      ['h2', 'Work That Usually Does Not'],
      ['ul', ['Interior and exterior painting', 'Flooring replacement', 'Cabinet and countertop replacement in the same layout, with no plumbing or electrical changes', 'Replacing a faucet, toilet, or light fixture in the same location', 'Minor drywall repair and trim work']],
      ['p', 'The gray area is where most kitchen and bath projects live. Swapping cabinets is cosmetic; adding an island with outlets and a prep sink is not. Re-tiling a shower may not need a permit; replacing the valve, moving the drain, or changing the footprint does. When in doubt, a quick call to the building department settles it.'],
      ['h2', 'Why Permits Are Worth It'],
      ['p', '<strong>Inspections catch what you cannot see.</strong> A second set of trained eyes on wiring, plumbing, and structure before the walls close is inexpensive insurance.'],
      ['p', '<strong>Unpermitted work surfaces at the worst time.</strong> Home inspectors, buyers\' agents, and insurers routinely compare a house against its permit history. Open or missing permits can delay a sale, reduce an offer, or complicate a claim.'],
      ['p', '<strong>In a flood zone, it is the only way to document compliance.</strong> Permit records establish what was spent and when, which matters under the <a href="/guides/fema-50-percent-rule-charlotte-county.html">FEMA 50% rule</a>.'],
      ['h2', 'Who Pulls the Permit?'],
      ['p', 'When you hire a licensed contractor, the contractor normally applies for the permit and is responsible for the work passing inspection. Florida does allow owner-builder permits for your own residence, but the owner then takes on the legal responsibility a contractor would carry, including supervising the work and using properly licensed trades. Be cautious of anyone who asks you to pull an owner-builder permit for work they will be doing.'],
      ['h2', 'How Long Does It Take?'],
      ['p', 'Simple trade permits are often issued quickly; projects requiring plan review take longer, and timelines stretch after major storms when departments are flooded with applications. A complete, well-prepared submittal is the best way to avoid delays.'],
      ['p', 'On every <a href="/services/kitchen-remodeling.html">kitchen remodeling</a>, <a href="/services/bathroom-remodeling.html">bathroom remodeling</a>, and <a href="/services/home-remodeling.html">home remodeling</a> project we perform, Brunderman Building Co Inc handles the permit applications and inspections for our work with the appropriate city or county.'],
      ['note', 'General information only — permit requirements are set by your local building department and change over time. Confirm what applies to your project and address before starting work.'],
    ],
    related: [['/services/kitchen-remodeling.html', 'Kitchen remodeling'], ['/services/bathroom-remodeling.html', 'Bathroom remodeling'], ['/locations/venice.html', 'Remodeling in Venice']],
  },
];
