// Location page content. Each city is written separately — different angles, different
// structure in the copy, real local references. Do NOT refactor these into a shared template.
// svc = one line per service, in SERVICES_NAV order.

module.exports = [
  {
    slug: 'port-charlotte',
    city: 'Port Charlotte',
    title: 'General Contractor in Port Charlotte, FL | Brunderman Building',
    description: 'General contractor in Port Charlotte, FL for new homes, remodels and additions. Four decades of local experience and 200+ homes built in Charlotte County.',
    eyebrow: 'Our Home Market · Charlotte County',
    h1: 'General Contractor in Port Charlotte, FL',
    lead: 'Port Charlotte is where we have done most of our building for four decades. If you need a general contractor who knows these streets, canals, and block homes, you have found one.',
    facts: [
      ['Population', 'About 60,000 (2020 Census)'],
      ['County', 'Charlotte County (unincorporated)'],
      ['From our office', 'Minutes away — our office is on Pinnacle St, off US-41'],
      ['Permits', 'Charlotte County Community Development'],
    ],
    intro: [
      'Port Charlotte was laid out in the late 1950s by General Development Corporation as one of the largest planned communities in Florida — tens of thousands of platted lots threaded with roughly 165 miles of canals. With around 60,000 residents today, it remains unincorporated, which means building permits run through Charlotte County rather than a city hall. Brunderman Building Co Inc has spent four decades working inside that system, and the majority of the 200-plus homes we have built in Charlotte County stand here.',
      'That history gives us an unusual familiarity with the housing stock. We know the low-slung 1960s and 70s block ranches off Edgewater Drive and Midway Boulevard, with their terrazzo floors and jalousie-era window openings. We know the 1980s and 90s homes around Murdock and the newer construction in Gulf Cove and South Gulf Cove. And we know what Hurricane Charley in 2004 and Hurricane Ian in 2022 did to roofs, soffits, lanais, and interiors across every one of those neighborhoods, because we were building here through both storms.',
      'Whether you are building new on a vacant lot in Section 15 or finally redoing the kitchen in a house you have owned for thirty years, working with a general contractor based right here in Port Charlotte keeps the project simple. Site visits are easy, suppliers are close, and the local permitting process is one we work with every week.',
    ],
    localH2: 'Building and Remodeling on Port Charlotte Lots',
    local: [
      'The typical Port Charlotte lot is about 80 feet wide and 125 feet deep. That standard footprint drives everything: where a three-car garage can fit, how deep a lanai and pool can go before hitting the rear setback, and whether an addition is possible without touching the septic drain field. Large areas of Port Charlotte are still on well and septic, while others have county water and sewer; the difference affects both new construction budgets and what can be added to an existing home.',
      'Canal lots add another layer. Saltwater canals with access to Charlotte Harbor through the Peace and Myakka rivers carry flood-zone designations that set the minimum finished-floor elevation for a new home, and the condition of the seawall matters to the whole project. Freshwater canal lots are generally simpler but still have drainage easements to respect. We evaluate all of this before you settle on a plan.',
    ],
    svc: [
      'New block homes on platted and canal-front lots, engineered for Charlotte County wind and flood requirements.',
      'Whole-house updates for GDC-era ranches — open layouts, impact windows, new floors and ceilings.',
      'Removing pass-throughs and soffits to open 1970s and 80s kitchens to the family room and lanai.',
      'Replacing alcove tubs and shower windows with waterproofed walk-in showers and better storage.',
      'Primary suites, in-law suites, and garage bays designed around 80-by-125-foot lot setbacks and septic fields.',
    ],
    seoH2: 'A Port Charlotte General Contractor Near You',
    seo: [
      'People searching for a general contractor near me in Port Charlotte FL, or for a Port Charlotte building contractor, tend to find a mix of out-of-area companies advertising into the market and a smaller group of builders who genuinely work here every week. Brunderman Building Co Inc is local in the literal sense: our office sits just off US-41 near the Charlotte Harbor bridges, a few minutes from the Port Charlotte Town Center and Charlotte Sports Park. More than 800 customers have hired us, and BuildZoom places us in the top 5% of builders.',
      'Our Port Charlotte work covers the full range — custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions. As a general contractor we coordinate every trade under one contract, handle Charlotte County permitting, and build to the Florida Building Code requirements for this wind-borne debris region. Homeowners choose a builder and remodeler with deep roots here because the advice is grounded in what has actually held up in Port Charlotte over forty years.',
    ],
    variantsH3: 'Port Charlotte Neighborhoods We Work In',
    variants: ['Gulf Cove and South Gulf Cove', 'Murdock and the Town Center area', 'Section 15 and the Edgewater Drive corridor', 'Harbour Heights and Charlotte Harbor', 'El Jobean and the Myakka River side', 'Peachland, Midway, and central Port Charlotte'],
    nearbyH3: 'Also Serving the Communities Around Port Charlotte',
    nearby: 'From our <a href="/">Port Charlotte home base</a>, the closest neighboring markets are <a href="/locations/punta-gorda.html">Punta Gorda across the Peace River</a> and <a href="/locations/north-port.html">North Port just over the Sarasota County line</a>. We also cover Deep Creek, Lake Suzy, Rotonda West, and the rest of Charlotte County as part of a service area that extends about 50 miles.',
    faqs: [
      ['Who issues building permits in Port Charlotte?', 'Because Port Charlotte is unincorporated, permits are issued by Charlotte County Community Development. We prepare and submit the application, coordinate the required engineering and surveys, and schedule inspections for the work we perform.'],
      ['Is my Port Charlotte lot in a flood zone?', 'Many are, especially near saltwater canals, the harbor, and the rivers. The flood zone and base flood elevation determine the minimum floor height for new construction and can affect how much remodeling is allowed under FEMA\'s 50% rule. We check this at the start of every project.'],
      ['Do you remodel older 1960s and 1970s Port Charlotte homes?', 'Regularly. Those concrete block homes are structurally sound and respond very well to remodeling — opening the kitchen, replacing windows with impact-rated units, updating baths, and adding a proper primary suite are all common projects for us.'],
    ],
  },

  {
    slug: 'punta-gorda',
    city: 'Punta Gorda',
    title: 'Home Builder & Remodeler in Punta Gorda, FL | Brunderman',
    description: 'Punta Gorda home builder and remodeler serving Punta Gorda Isles, Burnt Store Isles & the historic district. Waterfront custom homes and remodeling.',
    eyebrow: 'Charlotte County Seat · Waterfront Building',
    h1: 'Home Builder & Remodeler in Punta Gorda, FL',
    lead: 'From sailboat-access homes in Punta Gorda Isles to cottages on the brick streets downtown, we build and remodel in a city where waterfront rules and historic character both matter.',
    facts: [
      ['Population', 'About 19,500 (2020 Census)'],
      ['County', 'Charlotte County (county seat)'],
      ['From our office', 'Our Pinnacle St office carries a Punta Gorda address'],
      ['Permits', 'City of Punta Gorda Building Division'],
    ],
    intro: [
      'Punta Gorda is small — roughly 19,500 people — but it may be the most varied place we build. On one side of town are Punta Gorda Isles and Burnt Store Isles, deed-restricted canal communities where nearly every home has a dock and a view down a seawalled waterway toward Charlotte Harbor. On the other is one of Southwest Florida\'s oldest downtowns, with tin-roofed cottages, brick-paved streets, and a historic district the city actively protects.',
      'A home builder and remodeler working in Punta Gorda needs to be comfortable in both worlds. In PGI and BSI, the conversation is about flood elevation, seawall setbacks, maximizing the water view, and satisfying the architectural review requirements that many sections carry. In the historic district near Gilchrist Park and Retta Esplanade, it is about respecting original proportions and materials while quietly bringing wiring, plumbing, and wind resistance up to modern standards.',
      'Brunderman Building Co Inc has been part of this community for four decades. Our office address is in Punta Gorda, and after Hurricane Charley made landfall here in 2004 the rebuilding effort reshaped much of the city — including the way homes are now engineered. We carry those lessons into every project.',
    ],
    localH2: 'Waterfront and Historic Homes Need Different Expertise',
    local: [
      'Waterfront lots in Punta Gorda Isles and Burnt Store Isles sit in FEMA flood zones, and new homes must be built with the finished floor at or above the required elevation. That frequently means a stem-wall foundation with compacted fill, carefully planned driveway slopes, and garage floors set lower than living areas where allowed. For remodels of older ground-level PGI homes, FEMA\'s 50% substantial-improvement rule is a central planning issue: exceed the threshold and the entire home must be elevated or otherwise brought into compliance. We help owners scope and phase projects with that limit clearly in view.',
      'In the downtown historic district, exterior changes are subject to city review, and the right approach is usually restoration-minded: repairing rather than replacing where possible, matching siding profiles and window proportions, and keeping additions subordinate to the original structure. Inland neighborhoods such as Burnt Store Meadows and Deep Creek are more conventional, and well suited to straightforward custom homes and remodeling.',
    ],
    svc: [
      'Waterfront custom homes in PGI and BSI, elevated to flood requirements and oriented to the canal view.',
      'Renovations planned around the FEMA 50% rule for older ground-level canal homes.',
      'Kitchens reoriented so the island and sink look out over the pool and the water.',
      'Spa-style primary baths and accessible showers for owners planning to stay long term.',
      'Additions and enclosed lanais that respect seawall setbacks and community deed restrictions.',
    ],
    seoH2: 'A Punta Gorda Builder and Remodeling Contractor Near You',
    seo: [
      'If you are comparing custom home builders in Punta Gorda FL, or searching for a remodeling contractor near me for a home in the Isles, look closely at waterfront experience. Building beside a seawall is not the same as building inland. Soil conditions, elevation, corrosion-resistant fasteners and hardware, impact glass facing open water, and dock and lift coordination all come into play. Brunderman Building Co Inc has four decades of experience with exactly these conditions, a top 5% builder rating from BuildZoom, and more than 800 customers behind us.',
      'We offer the same core services in Punta Gorda that we do across Charlotte County: custom home construction, whole-home remodeling, kitchen remodeling, bathroom remodeling, and home additions. The City of Punta Gorda runs its own building division, separate from the county, and we are accustomed to its submittal and inspection process. One reviewer called us "the most experienced builders in the area" — in a city with this many specialized requirements, that experience is the point.',
    ],
    variantsH3: 'Where We Work in Punta Gorda',
    variants: ['Punta Gorda Isles (PGI)', 'Burnt Store Isles (BSI)', 'Downtown historic district', 'Burnt Store Meadows', 'Deep Creek', 'Burnt Store Road corridor and Burnt Store Marina area'],
    nearbyH3: 'Nearby Service Areas',
    nearby: 'Punta Gorda is at the center of our territory. Across the US-41 bridges is <a href="/locations/port-charlotte.html">Port Charlotte, where most of our homes have been built</a>, and heading south on Burnt Store Road leads directly into <a href="/locations/cape-coral.html">northwest Cape Coral</a>. See the <a href="/">Brunderman Building Co Inc homepage</a> for the full 50-mile service area.',
    faqs: [
      ['Do you build in Punta Gorda Isles and Burnt Store Isles?', 'Yes. We build new waterfront homes and remodel existing ones in both communities, and we work within the deed restrictions and architectural review requirements that apply to many sections.'],
      ['My PGI home is at ground level. How much remodeling can I do?', 'If the home is below the current required flood elevation, improvements are limited by FEMA\'s 50% rule as administered by the City of Punta Gorda. The limit is based on the value of the structure, not the land. We help you understand the numbers before designing the project.'],
      ['Can you work on a home in the historic district?', 'We can. Exterior work in the district typically requires city review, and we plan projects to be compatible with the home\'s original character while improving its structure, systems, and storm resistance.'],
    ],
  },

  {
    slug: 'north-port',
    city: 'North Port',
    title: 'Home Builder & Remodeler in North Port, FL | Brunderman',
    description: 'North Port, FL home builder and remodeler. Build on your lot, remodel a kitchen or bath, or add on — four decades of Southwest Florida experience.',
    eyebrow: 'Sarasota County · Build On Your Lot',
    h1: 'Home Builder & Remodeler in North Port, FL',
    lead: 'North Port has more buildable lots than almost anywhere in the region. We help owners turn them into custom homes — and help longtime residents remodel the houses they already have.',
    facts: [
      ['Population', 'About 75,000 (2020 Census) and growing fast'],
      ['County', 'Sarasota County'],
      ['From our office', 'Roughly 10–15 miles north via US-41 or I-75'],
      ['Permits', 'City of North Port Building Division'],
    ],
    intro: [
      'By land area, North Port is one of the largest cities in Florida, and for years much of it was empty: thousands of platted lots along quiet streets off Toledo Blade, Sumter, and Price boulevards, waiting for someone to build. That has changed quickly. The 2020 Census counted about 75,000 residents, and the number has climbed every year since, making North Port one of the fastest-growing cities in the state.',
      'For a custom home builder, North Port is a build-on-your-lot market. Many of our clients here bought a lot years ago — or inherited one — and are now ready to build. Others are relocating and have discovered that a vacant lot plus a custom home can compare well with buying in one of the master-planned communities out in Wellen Park. Either way, the process starts with understanding the lot, and that is where an experienced home builder and remodeler earns its keep.',
      'We are just down the road. Brunderman Building Co Inc is based a short drive south in Charlotte County, where we have built more than 200 homes over four decades. North Port and Port Charlotte were platted by the same developer, with the same lot dimensions and much the same soil and drainage, so the work is second nature.',
    ],
    localH2: 'What to Know Before Building in North Port',
    local: [
      'Most undeveloped North Port lots rely on a private well and a septic system, because city water and sewer reach only part of the platted area. The septic system type is determined by soil and water-table conditions, and the required drain field can take up a meaningful part of the lot — which affects where the house, driveway, and any future pool can go. Lots also need to be checked for protected species: gopher tortoise burrows and scrub-jay habitat both occur here and must be addressed through the proper process before clearing.',
      'None of this is a reason not to build; it simply needs to be budgeted and scheduled. We walk North Port owners through lot clearing, fill, well and septic, culvert and driveway requirements, and city impact fees up front, so the price of the home reflects the real cost of building on that particular piece of ground. For established neighborhoods like Heron Creek, Bobcat Trail, and Sabal Trace, the conversation shifts to remodeling homes from the 1990s and 2000s that are due for new kitchens, baths, and flooring.',
    ],
    svc: [
      'Build-on-your-lot custom homes, including clearing, fill, well, septic, and driveway site work.',
      'Interior renovations for 1990s–2000s homes in established golf and lake communities.',
      'Builder-grade kitchens replaced with real cabinetry, quartz, and an island that fits how you cook.',
      'Garden tubs removed in favor of large tiled walk-in showers and double vanities.',
      'Extra bedrooms, offices, and garage space, sited clear of the well and septic drain field.',
    ],
    seoH2: 'North Port Home Builders and Remodelers Near You',
    seo: [
      'Search for home builders near me in North Port FL and you will see large regional production builders alongside local custom builders. The production companies are efficient at building their own plans in their own communities. If you want a specific plan on your own lot — or you want to change the plan — a custom builder is the better fit. Brunderman Building Co Inc builds one home at a time for the person who will live in it, backed by four decades of experience, a top 5% BuildZoom rating, and the trust of more than 800 customers.',
      'Our North Port services include custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions. The City of North Port operates its own building department, and we handle the permit submittals, engineering coordination, and inspections. After Hurricane Ian flooded parts of North Port in 2022, particularly near the Myakkahatchee Creek, many homeowners also needed a remodeling contractor for interior rebuilds — work we know well and continue to perform.',
    ],
    variantsH3: 'North Port Projects We Commonly See',
    variants: ['Custom homes on platted lots off Toledo Blade and Price boulevards', 'Well, septic, and site work packages for vacant lots', 'Kitchen and bath remodeling in Heron Creek and Bobcat Trail', 'Post-storm interior rebuilds and flooring replacement', 'Garage additions and workshop space on oversized lots', 'Remodels near Warm Mineral Springs and North Port Estates acreage'],
    nearbyH3: 'Neighboring Areas We Serve',
    nearby: 'North Port sits between two of our other markets: <a href="/locations/port-charlotte.html">Port Charlotte to the south</a>, which shares the same platted-lot layout, and <a href="/locations/venice.html">the Venice area to the northwest</a> along US-41 and I-75. Learn more about our company on the <a href="/">main Brunderman Building Co Inc page</a>.',
    faqs: [
      ['I own a vacant lot in North Port. Can you build on it?', 'Very likely. We start with a lot evaluation covering flood zone, fill requirements, well and septic feasibility, protected species, and access. Once we know what the lot requires, we can price the site work together with the home.'],
      ['Will my North Port lot need a well and septic system?', 'Many do. City utilities serve only portions of North Port. If water and sewer are not available at your lot, a private well and an approved septic system are part of the build, and we coordinate both.'],
      ['Do you work in Wellen Park?', 'Most new homes in Wellen Park are built by the community\'s designated builders. We are available there for remodeling and improvement work on existing homes, subject to the community\'s rules for outside contractors.'],
    ],
  },

  {
    slug: 'englewood',
    city: 'Englewood',
    title: 'Home Builder & Remodeler in Englewood, FL | Brunderman',
    description: 'Englewood, FL home builder and remodeler serving Rotonda West, Manasota Key & Cape Haze. Coastal custom homes, remodels, kitchens and baths.',
    eyebrow: 'Two Counties · One Coastline',
    h1: 'Home Builder & Remodeler in Englewood, FL',
    lead: 'Englewood straddles two counties and faces the Gulf. Building and remodeling here takes a contractor who understands coastal construction and knows which building department your address belongs to.',
    facts: [
      ['Population', 'About 20,800 (2020 Census)'],
      ['County', 'Split between Charlotte and Sarasota counties'],
      ['From our office', 'About 20–25 miles west via SR 776'],
      ['Permits', 'Charlotte County or Sarasota County, depending on address'],
    ],
    intro: [
      'Englewood is an unincorporated coastal community of about 20,800 people, and the Charlotte–Sarasota county line runs right through it. A house north of the line answers to Sarasota County\'s building department; one a few blocks south answers to Charlotte County\'s. Permit procedures, zoning rules, and even flood-plain administration differ between the two, so the first question on any Englewood project is simply: which side are you on?',
      'The second question is how close you are to the water. Lemon Bay separates the mainland from Manasota Key, and homes along the bay and on the key face the most demanding building conditions in our service area — high-velocity flood zones, coastal construction setbacks, and wind exposure straight off the Gulf of Mexico. Farther inland, Rotonda West\'s circular plan of golf-course and canal lots, along with Cape Haze and the neighborhoods off Dearborn Street in Old Englewood Village, offer more conventional sites for custom homes and remodeling.',
      'Brunderman Building Co Inc has worked along this coast for four decades. Hurricane Ian\'s 2022 landfall hit Englewood hard, and a large share of the home remodeling work in the area since has been rebuilding — roofs, windows, drywall, kitchens, and baths in homes that took wind and water.',
    ],
    localH2: 'Coastal Construction on Lemon Bay and Manasota Key',
    local: [
      'In coastal high-hazard (VE) flood zones, which cover much of Manasota Key and the bayfront, new homes are built on pilings or columns with the living floor elevated above the base flood elevation, and the area underneath limited to parking, storage, and access with breakaway walls. State coastal construction control line rules can also apply on the Gulf side. These homes require specialized engineering, corrosion-resistant connectors and fasteners, and impact-rated openings designed for higher wind pressures. They also reward good design: elevated living areas have remarkable views.',
      'Inland, Rotonda West and the surrounding subdivisions are primarily slab-on-grade concrete block homes much like those in Port Charlotte, many on lots backing to golf fairways or freshwater canals. Deed restrictions in Rotonda govern things like minimum square footage and exterior appearance, and we account for those at the design stage.',
    ],
    svc: [
      'Elevated coastal homes and block homes on Rotonda West golf and canal lots.',
      'Storm-damage rebuilds and full interior renovations for homes on both sides of the county line.',
      'Light, coastal-style kitchens with durable finishes suited to salt air and seasonal use.',
      'Low-maintenance tiled showers and updated baths for seasonal and full-time residents.',
      'Guest suites and enclosed lanais, designed to the flood and setback rules for your address.',
    ],
    seoH2: 'Englewood Building Contractor and Remodeler Near You',
    seo: [
      'Homeowners who search for a building contractor near me in Englewood FL, or for Englewood home remodeling, often run into contractors who work on only one side of the county line. We work on both. Brunderman Building Co Inc prepares permit submittals for Charlotte County and Sarasota County alike, and we understand how each administers flood-plain rules such as FEMA\'s 50% substantial-improvement limit — a major factor for older ground-level homes near Lemon Bay.',
      'Our Englewood services include custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions. We are rated in the top 5% of builders by BuildZoom and have served more than 800 customers across the region. For seasonal residents, we are used to coordinating projects while the owner is up north — clear written scopes, regular photo updates, and a home that is ready when you return for the winter.',
    ],
    variantsH3: 'Englewood-Area Communities We Serve',
    variants: ['Rotonda West and Rotonda Lakes', 'Manasota Key and Englewood Beach', 'Old Englewood Village and the Dearborn Street area', 'Cape Haze and Placida', 'Englewood Isles and Lemon Bay waterfront', 'South Gulf Cove and Gulf Cove along SR 776', 'Boca Grande (Gasparilla Island)'],
    nearbyH3: 'Nearby Areas',
    nearby: 'State Road 776 connects Englewood east to <a href="/locations/port-charlotte.html">our home market in Port Charlotte</a>, and River Road or SR 776 north leads to <a href="/locations/venice.html">Venice and South Venice</a>. Start at the <a href="/">Brunderman Building Co Inc home page</a> to see everything we do.',
    faqs: [
      ['Is my Englewood home in Charlotte County or Sarasota County?', 'It depends on the address — the county line runs through the community. Your property tax bill will tell you. We work with both building departments, so either way we can handle the permitting.'],
      ['Do you build elevated homes on pilings?', 'Yes. In VE flood zones on Manasota Key and along the bay, elevated construction is required, and we coordinate the structural engineering, foundation, and code-compliant enclosure below the living floor.'],
      ['I am a seasonal resident. Can you remodel while I am away?', 'Many of our Englewood clients are seasonal. With selections made and a written scope agreed before you leave, we can complete the work during the off-season and keep you updated with photos and calls.'],
    ],
  },

  {
    slug: 'venice',
    city: 'Venice',
    title: 'Home Builder & Remodeler in Venice, FL | Brunderman Building',
    description: 'Venice, FL home builder and remodeler. Remodeling for island homes, South Venice & Venice Gardens, plus custom homes and additions. 4 decades of experience.',
    eyebrow: 'Sarasota County · Gulf Coast',
    h1: 'Home Builder & Remodeler in Venice, FL',
    lead: 'Venice was planned as a showpiece city in the 1920s, and it still takes its architecture seriously. We remodel and build here with that character — and the Gulf weather — in mind.',
    facts: [
      ['Population', 'About 25,500 (2020 Census)'],
      ['County', 'Sarasota County'],
      ['From our office', 'Roughly 30 miles northwest via I-75 or US-41'],
      ['Permits', 'City of Venice or Sarasota County, depending on address'],
    ],
    intro: [
      'Few Florida towns have a pedigree like Venice. The city\'s layout was drawn in 1926 by John Nolen, one of the country\'s pioneering urban planners, with broad boulevards, parks, and a Northern Italian architectural theme that still defines West Venice Avenue and the historic neighborhoods on the island. About 25,500 people live within the city limits, and a good many more in the unincorporated areas around it — South Venice, Venice Gardens, Nokomis, and the newer communities east of I-75 along Jacaranda Boulevard.',
      'For a home builder and remodeler, that mix produces very different projects within a few miles of each other. On the island, we are often asked to update a mid-century or Mediterranean Revival home without losing what makes it charming: barrel-tile roofs, arched openings, stucco detailing. In South Venice and Venice Gardens, the work is practical remodeling of 1960s–80s block homes on modest lots. Out east, it is kitchens, baths, and additions in 1990s and 2000s subdivisions.',
      'Venice is at the northern end of Brunderman Building Co Inc\'s 50-mile service radius, about half an hour up I-75 from our Charlotte County base. We take on projects here selectively and staff them properly, bringing the same four decades of experience that built more than 200 homes to the south.',
    ],
    localH2: 'Remodeling Around Venice\'s Architecture and Review Process',
    local: [
      'Parts of the City of Venice fall within historic and architectural control districts where exterior changes — windows, doors, roofing, additions, even colors in some cases — go before the city\'s review board. Approval is very achievable when the design respects the district\'s Northern Italian and Mediterranean vocabulary, and we plan submittals accordingly. Replacing original windows with impact-rated units that keep the right proportions and muntin patterns is a typical example of balancing preservation with storm protection.',
      'Outside the city limits, Sarasota County handles permitting, and the concerns are more familiar: flood zones near the Intracoastal Waterway, Roberts Bay, and the Myakka River; septic systems in South Venice; and homeowner association approvals in the gated communities. Knowing at the outset whether an address is city or county saves time, and we confirm it before any design work begins.',
    ],
    svc: [
      'Custom homes on infill and teardown lots, designed to fit established Venice streetscapes.',
      'Character-sensitive renovations on the island and practical updates in South Venice and Venice Gardens.',
      'Kitchen renovations that open compact mid-century layouts while keeping period charm.',
      'Bathroom remodeling with accessible showers for Venice\'s many long-term and retired residents.',
      'Primary suites, Florida rooms, and garage additions reviewed against city or county setbacks.',
    ],
    seoH2: 'Venice Remodeling Contractor and Home Builder Near You',
    seo: [
      'Anyone looking up a remodeling contractor near me in Venice FL will find no shortage of options, so it is fair to ask why a Charlotte County builder is worth a call. The answer is depth of experience. Brunderman Building Co Inc has spent four decades building and remodeling concrete block homes in the same climate, under the same Florida Building Code, a few exits down the interstate. We are rated in the top 5% of builders on BuildZoom, more than 800 customers have hired us, and our reviewers consistently mention professionalism, punctuality, and quality.',
      'In Venice we provide home remodeling, kitchen remodeling, bathroom remodeling, home additions, and custom home construction. Because so much of the local housing dates from the 1950s through the 1980s, remodeling is the most common request: replacing original kitchens and baths, swapping jalousie and single-pane windows for impact glass, removing walls to open the living area, and upgrading electrical service for modern loads. We handle the design coordination, the permits with the City of Venice or Sarasota County, and every trade involved.',
    ],
    variantsH3: 'Venice-Area Neighborhoods',
    variants: ['Venice Island and the historic districts', 'South Venice', 'Venice Gardens', 'Nokomis and Laurel', 'Jacaranda Boulevard and east-of-I-75 communities', 'Golden Beach and the Venice Avenue corridor'],
    nearbyH3: 'Areas Near Venice We Also Cover',
    nearby: 'South of Venice, our work continues into <a href="/locations/north-port.html">North Port and the Wellen Park area</a> and down the coast to <a href="/locations/englewood.html">Englewood and Manasota Key</a>. For an overview of the company, visit the <a href="/">Brunderman Building Co Inc homepage</a>.',
    faqs: [
      ['Do you travel to Venice from Port Charlotte?', 'Yes. Venice is within our 50-mile service area, about a half-hour drive up I-75. We schedule Venice projects so crews and supervision are on site consistently, just as they would be closer to home.'],
      ['My home is in a Venice historic district. Can I replace the windows?', 'Generally yes, with approval. The city\'s review process looks at whether new windows are compatible with the home\'s architecture. We select impact-rated products with appropriate proportions and prepare the submittal.'],
      ['Is my address in the City of Venice or unincorporated Sarasota County?', 'Many "Venice" mailing addresses — including South Venice and Venice Gardens — are actually in unincorporated Sarasota County. We verify the jurisdiction at the start because it determines where permits are filed and which zoning rules apply.'],
    ],
  },

  {
    slug: 'cape-coral',
    city: 'Cape Coral',
    title: 'Home Builder & Remodeler in Cape Coral, FL | Brunderman',
    description: 'Cape Coral, FL home builder and remodeler for canal-front custom homes, kitchen & bath remodeling and additions. Four decades of SW Florida experience.',
    eyebrow: 'Lee County · 400 Miles of Canals',
    h1: 'Home Builder & Remodeler in Cape Coral, FL',
    lead: 'Cape Coral has more canal frontage than any city in the world. We build and remodel homes here with the same waterfront know-how we have used on Charlotte County canals for forty years.',
    facts: [
      ['Population', 'About 194,000 (2020 Census)'],
      ['County', 'Lee County'],
      ['From our office', 'Roughly 25–30 miles south via Burnt Store Road'],
      ['Permits', 'City of Cape Coral'],
    ],
    intro: [
      'With about 194,000 residents in the 2020 Census, Cape Coral is by far the largest city in our service area, and it is still filling in. The Rosen brothers began dredging it out of the mangroves in 1957, and the result is a grid of some 400 miles of canals — some freshwater, some saltwater with access to the Caloosahatchee River, Matlacha Pass, and the Gulf. Locals navigate by quadrant: the established Southeast and Southwest Cape, and the rapidly developing Northwest and Northeast.',
      'Our connection to Cape Coral is geographic. Burnt Store Road runs straight from Punta Gorda into the Northwest Cape, which puts that quadrant — where a great deal of today\'s custom home construction is happening — closer to our office than to parts of Fort Myers. Owners with Gulf-access lots off Old Burnt Store Road, or freshwater lots north of Pine Island Road, regularly look north for a home builder and remodeler with long waterfront experience.',
      'Brunderman Building Co Inc brings four decades of that experience, along with a record of more than 200 homes built one county up. The canal lots of Port Charlotte and Punta Gorda pose the same questions as Cape Coral\'s: flood elevation, seawalls, fill, dock planning, and how to aim the house at the view.',
    ],
    localH2: 'Gulf Access, Freshwater, and the Utility Expansion',
    local: [
      'The first thing to establish on a Cape Coral lot is what kind of water it fronts. Gulf-access canals carry saltwater flood-zone designations and command designs that make the most of the rear exposure — southern and western views are especially prized for afternoon sun on the pool. Freshwater canal and dry lots are simpler and more affordable to build on but still require attention to fill and finished-floor elevation.',
      'The second is utilities. Cape Coral has been extending city water, sewer, and irrigation across the north end in phases through its Utilities Extension Project, with assessments charged to each lot. Where city utilities have not yet arrived, a new home needs a well and septic system now and will connect later. We factor the current status of your specific lot into the construction budget. For existing homes in the older Southeast and Southwest Cape — around Cape Coral Parkway, the Yacht Club area, and Pelican — remodeling after Hurricane Ian\'s 2022 surge and wind damage has been a large part of the work.',
    ],
    svc: [
      'Canal-front custom homes in the Northwest and Southwest Cape, elevated and oriented for the water view.',
      'Post-Ian rebuilds and full renovations of 1970s–90s homes in the Southeast and Southwest Cape.',
      'Open, island-centered kitchens that look through sliders to the lanai, pool, and canal.',
      'Primary bath overhauls plus pool-bath updates for homes that live outdoors.',
      'Extended lanais, guest suites, and garage additions designed around seawall setbacks.',
    ],
    seoH2: 'Cape Coral Home Builder and Remodeler Near You',
    seo: [
      'Typing custom home builder near me in Cape Coral FL brings up dozens of names, from high-volume builders putting up the same few models across the north end to boutique firms focused on luxury Gulf-access homes. Brunderman Building Co Inc sits between those extremes: a true custom builder with the experience to handle a complex waterfront home and the practicality to build a well-priced family home on a freshwater lot. BuildZoom rates us among the top 5% of builders, and more than 800 customers have trusted us with their projects.',
      'We offer Cape Coral homeowners custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions. As a general contractor we coordinate permitting with the City of Cape Coral, manage every trade, and build to the Florida Building Code standards for wind-borne debris regions — impact-rated openings, engineered roof connections, and proper elevation. If you own a ground-level home in a flood zone, we will also explain how the FEMA 50% rule affects your remodeling options before you spend money on design.',
    ],
    variantsH3: 'Parts of Cape Coral We Serve',
    variants: ['Northwest Cape and the Burnt Store Road corridor', 'Southwest Cape, Cape Harbour, and Tarpon Point', 'Southeast Cape and the Yacht Club area', 'Northeast Cape and the Pine Island Road corridor', 'Gulf-access, freshwater canal, and dry lots', 'Matlacha and the Pine Island approach'],
    nearbyH3: 'Nearby Service Areas',
    nearby: 'Cape Coral connects north along Burnt Store Road to <a href="/locations/punta-gorda.html">Punta Gorda and Burnt Store Isles</a>, and east across the Caloosahatchee bridges to <a href="/locations/fort-myers.html">Fort Myers</a>. Read more about our background on the <a href="/">Brunderman Building Co Inc main page</a>.',
    faqs: [
      ['Do you build in Northwest Cape Coral?', 'Yes. The Northwest Cape is the closest part of the city to our office, reached directly by Burnt Store Road, and it is where much of the available Gulf-access and freshwater land is located.'],
      ['Does my Cape Coral lot have city water and sewer?', 'It depends on whether the Utilities Extension Project has reached your area. If not, the home will need a well and septic system initially. We confirm the status of your lot and include the appropriate costs in your budget.'],
      ['Can you remodel a home that flooded during Hurricane Ian?', 'We can. Rebuilds typically involve new drywall, insulation, cabinetry, flooring, doors, and electrical devices, and in flood zones the scope has to be evaluated against the FEMA 50% rule. We help you work through both the construction and the compliance questions.'],
    ],
  },

  {
    slug: 'fort-myers',
    city: 'Fort Myers',
    title: 'Home Builder & Remodeler in Fort Myers, FL | Brunderman',
    description: 'Fort Myers, FL home builder and remodeler — remodeling for McGregor corridor & historic homes, custom homes and additions. Four decades of experience.',
    eyebrow: 'Lee County Seat · Caloosahatchee River',
    h1: 'Home Builder & Remodeler in Fort Myers, FL',
    lead: 'Fort Myers is the oldest and most architecturally varied city we serve. From riverfront estates off McGregor Boulevard to 1920s bungalows, we bring a builder\'s judgment to every remodel and new home.',
    facts: [
      ['Population', 'About 86,000 (2020 Census)'],
      ['County', 'Lee County (county seat)'],
      ['From our office', 'About 25–30 miles south via I-75 or US-41'],
      ['Permits', 'City of Fort Myers or Lee County, depending on address'],
    ],
    intro: [
      'Thomas Edison built his winter estate on the Caloosahatchee River in the 1880s and later lined McGregor Boulevard with the royal palms that gave Fort Myers its "City of Palms" nickname. The city that grew up around those estates — about 86,000 residents as of 2020, and the seat of Lee County — has a range of housing unlike anywhere else in our service area: century-old bungalows in Dean Park, mid-century ranches in Whiskey Creek, riverfront homes off McGregor, and brand-new subdivisions stretching east toward Gateway and I-75.',
      'That variety calls for judgment more than formula. A 1925 frame bungalow and a 2005 stucco two-story need entirely different approaches to a kitchen remodel. One may have plaster walls, a crawl space, and wiring that has to be replaced before anything else happens; the other may just need better design and better materials. A home builder and remodeler with four decades behind it has seen both many times over.',
      'Fort Myers lies at the southern edge of Brunderman Building Co Inc\'s territory, a straight run down I-75 from our Charlotte County office. We have built more than 200 homes to the north, earned a top 5% rating on BuildZoom, and served more than 800 customers — and we bring that same standard across the county line.',
    ],
    localH2: 'Older Homes, River Flooding, and Building in Lee County',
    local: [
      'Fort Myers\' historic neighborhoods — Dean Park, Edison Park, Seminole Park, and the streets near the River District — contain some of the oldest homes in Southwest Florida. Remodeling them often begins with the unglamorous work: replacing cast-iron drains and cloth-insulated wiring, leveling floors over pier foundations, adding insulation and proper HVAC to houses designed for cross-breezes. The city\'s historic preservation rules apply to exterior changes in designated districts, and we design within them.',
      'Along the Caloosahatchee, Hurricane Ian\'s 2022 storm surge pushed well up the river and flooded homes that had stayed dry for generations. For riverfront and near-river properties off McGregor Boulevard, flood elevation and the FEMA 50% rule are now central to any substantial renovation. East of US-41 and out toward Gateway, conditions are easier: newer block homes on higher ground, where remodeling and home additions are chiefly a matter of design, HOA approval, and good execution.',
    ],
    svc: [
      'Custom homes on infill lots and acreage, plus teardown-and-rebuild projects near the river.',
      'Systems-first renovations of historic bungalows and full updates of mid-century ranches.',
      'Kitchen remodeling that suits the era of the house — from period-appropriate to fully modern.',
      'Bathroom remodeling including re-piping, waterproofed tile showers, and added primary baths.',
      'Additions that match older rooflines and details, or expand newer homes in HOA communities.',
    ],
    seoH2: 'Fort Myers Remodeling Contractor and Builder Near You',
    seo: [
      'If you have searched for a general contractor near me in Fort Myers FL or for Fort Myers home remodeling, you already know the market is crowded, particularly since the hurricane. What separates contractors is track record. Brunderman Building Co Inc did not arrive after the storm; we have been building and remodeling homes in Southwest Florida for four decades. Our reviewers describe responsiveness, punctuality, quality, professionalism, and value — the basics that matter most when someone is working on your home.',
      'For Fort Myers clients we provide home remodeling, kitchen remodeling, bathroom remodeling, home additions, and custom home construction. Addresses inside the city limits are permitted through the City of Fort Myers, while much of what people call Fort Myers — including areas toward Gateway, San Carlos, and south along US-41 — is unincorporated and permitted by Lee County. We work with both, manage all trades under a single contract, and build to current Florida Building Code wind and flood standards.',
    ],
    variantsH3: 'Fort Myers Neighborhoods We Serve',
    variants: ['McGregor Boulevard corridor and riverfront', 'Dean Park, Edison Park, and the River District', 'Whiskey Creek', 'Gateway and east Fort Myers', 'North Fort Myers', 'Buckingham and rural acreage east of I-75'],
    nearbyH3: 'Nearby Areas We Cover',
    nearby: 'Just across the river bridges is <a href="/locations/cape-coral.html">Cape Coral, with its hundreds of miles of canals</a>, and north on I-75 brings you to <a href="/locations/punta-gorda.html">Punta Gorda and Charlotte Harbor, where our office is located</a>. The <a href="/">Brunderman Building Co Inc homepage</a> outlines our full service area and history.',
    faqs: [
      ['Is Fort Myers within your service area?', 'Yes. Fort Myers is roughly 25 to 30 miles from our office, well inside our 50-mile radius. North Fort Myers is closer still.'],
      ['Do you remodel historic homes in Fort Myers?', 'We do. Older homes usually need mechanical, electrical, and structural updates along with the visible improvements, and exterior changes in designated historic districts require city approval. We plan for both from the start.'],
      ['Is my property permitted by the City of Fort Myers or Lee County?', 'It depends on whether the address is inside the city limits — many Fort Myers mailing addresses are not. We confirm the jurisdiction before design begins because it determines zoning rules and where permits are filed.'],
    ],
  },
];
