// Location page content. Each city is written separately — different angles, different
// structure in the copy, real local references. Do NOT refactor these into a shared template.
// svc = one line per service, in SERVICES_NAV order.

module.exports = [
  {
    slug: 'charlotte-county',
    city: 'Charlotte County',
    areaType: 'AdministrativeArea',
    title: 'Home Builder & Remodeler in Charlotte County, FL | Brunderman',
    description: 'Charlotte County, FL home builder and remodeler since 1987, with 200+ homes built county-wide. Hurricane-proof custom homes, remodels, kitchens and baths.',
    eyebrow: 'County-Wide · Building Here Since 1987',
    h1: 'Home Builder & Remodeler in Charlotte County, FL',
    lead: 'More than 200 of the homes we have built stand in Charlotte County. From Englewood to Babcock Ranch and from El Jobean to Burnt Store, this county is where we have spent four decades building and remodeling.',
    facts: [
      ['Population', 'About 187,000 (2020 Census)'],
      ['County seat', 'Punta Gorda, the only incorporated city'],
      ['Our office', 'Pinnacle St, near Charlotte Harbor and US-41'],
      ['Permits', 'Charlotte County Community Development; City of Punta Gorda inside city limits'],
    ],
    intro: [
      'Charlotte County stretches from the Gulf beaches of Manasota Key and Gasparilla Island, across Charlotte Harbor and the mouths of the Peace and Myakka rivers, to the ranchland east of I-75. About 187,000 people live here, and most of them live outside any city limits. Punta Gorda is the county\'s only incorporated city; everything else — Port Charlotte, the Charlotte County side of Englewood, Rotonda West, Deep Creek, Harbour Heights, Babcock Ranch — is unincorporated and governed directly by the county. For a home builder and remodeler, that means one building department handles most of the work, and knowing how it operates is half the job.',
      'Brunderman Building Co Inc has worked in Charlotte County since Brian Brunderman founded the company in 1987. More than 200 of the homes we have built are here, along with the remodels, kitchens, baths, and additions we have done for a large share of the 800-plus customers we have served. We have built on quarter-acre platted lots, on sailboat-access canals, on coastal lots on the west side of the county, and on acreage well east of the interstate. The details change from one end of Charlotte County to the other. The standard does not.',
      'That standard is our motto: houses shouldn\'t break. Hurricane Charley came ashore near Punta Gorda in August 2004 as a Category 4 storm, and Hurricane Ian brought wind and surge back across the county in 2022. Both storms showed, street by street, which homes were built properly and which were not. Every custom home and remodel we take on here is built to be a hurricane-proof home: concrete block walls, engineered roof connections, impact-rated windows and doors, and floors set at or above the flood line.',
    ],
    localH2: 'West County, Mid County, South County, and East County',
    local: [
      'People who live here divide Charlotte County into four parts, and each one builds differently. West County — Englewood, Rotonda West, Cape Haze, Placida, Grove City, and the Charlotte County ends of Manasota Key and Gasparilla Island — is coastal: high-hazard flood zones near the water, elevated construction on the islands, and the circular canal and golf-course lots of Rotonda. Mid County is Port Charlotte, Murdock, El Jobean, Charlotte Harbor, and Harbour Heights, where the 80-by-125-foot platted lots and roughly 165 miles of canals laid out in the late 1950s still shape almost every project.',
      'South County means Punta Gorda, Punta Gorda Isles, Burnt Store Isles, and the Burnt Store Road corridor, where waterfront building runs through the City of Punta Gorda\'s own building division. East County is changing fastest: Babcock Ranch, the solar-powered town that drew national attention for how well it came through Hurricane Ian, and the rural acreage along State Roads 31 and 74 where wells, septic systems, and long driveways are the norm. We work in all four areas and plan each project around the flood zone, utilities, and permitting rules for that specific address.',
    ],
    svc: [
      'Hurricane-proof custom homes on platted, canal-front, coastal, and acreage lots anywhere in the county.',
      'Whole-home remodels that bring 1960s–1990s block homes up to modern layouts and storm standards.',
      'Kitchens opened to the lanai and the water view, with impact-rated sliders replacing aging glass.',
      'Walk-in showers, accessible baths, and pool baths built with real waterproofing for Florida humidity.',
      'Primary suites, in-law suites, garages, and enclosed lanais sited around setbacks, septic, and flood rules.',
    ],
    seoH2: 'A Charlotte County Home Builder Near You',
    seo: [
      'If you are searching for a home builder near me in Charlotte County FL, a remodeling contractor for a house in Rotonda West, or a custom home builder for acreage out toward Babcock Ranch, you want someone who works here every week — not a company that drives in for one job and leaves. Brunderman Building Co Inc is based on Pinnacle Street near Charlotte Harbor, in the middle of the county, and has been building here for four decades. BuildZoom rates us among the top 5% of builders, and we are available 24/7.',
      'Our Charlotte County services include custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions, all under one contract. As a general contractor we handle Charlotte County Community Development permitting for unincorporated addresses and the City of Punta Gorda for addresses inside city limits, coordinate every trade, and build hurricane-proof homes with impact-rated windows to the Florida Building Code requirements for a wind-borne debris region. Whether the project is a new home in Port Charlotte or a remodel near Englewood Beach, it gets the same builder and the same standard.',
    ],
    variantsH3: 'Charlotte County Communities We Serve',
    variants: ['Port Charlotte, Murdock, and Charlotte Harbor', 'Punta Gorda, Punta Gorda Isles, and Burnt Store Isles', 'Englewood (Charlotte County side), Rotonda West, and Cape Haze', 'Placida, Grove City, and Manasota Key', 'Boca Grande on Gasparilla Island', 'Deep Creek, Harbour Heights, and El Jobean', 'Babcock Ranch and East County acreage', 'Gulf Cove, South Gulf Cove, and Burnt Store'],
    nearbyH3: 'More on Building in Charlotte County',
    nearby: 'For detail on the county\'s two largest communities, see our pages on <a href="/locations/port-charlotte.html">general contracting in Port Charlotte</a> and <a href="/locations/punta-gorda.html">building and remodeling in Punta Gorda</a>. Just north of the county line we also serve <a href="/locations/north-port.html">North Port</a> and <a href="/locations/venice.html">Venice</a> in Sarasota County. Start at the <a href="/">Brunderman Building Co Inc homepage</a> for everything we do.',
    faqs: [
      ['Do you work everywhere in Charlotte County?', 'Yes. Our office is near Charlotte Harbor, in the middle of the county, and we build and remodel from Englewood and Manasota Key on the west side to Babcock Ranch and the rural acreage on the east side, and from El Jobean south to Burnt Store.'],
      ['Who issues building permits in Charlotte County?', 'For unincorporated areas — most of the county, including Port Charlotte, the Charlotte County side of Englewood, Rotonda West, and Deep Creek — permits are issued by Charlotte County Community Development. Inside Punta Gorda city limits, the City of Punta Gorda issues them. We handle the applications and inspections for the work we perform.'],
      ['Can you build or remodel in Babcock Ranch?', 'Babcock Ranch has its own builder program and design rules, so the answer depends on the project. Call us and we will tell you what is possible for your address. We also build custom homes on acreage elsewhere in East County.'],
    ],
  },

  {
    slug: 'port-charlotte',
    city: 'Port Charlotte',
    title: 'General Contractor in Port Charlotte, FL | Brunderman Building',
    description: 'General contractor in Port Charlotte, FL for new homes, remodels and additions. Four decades of local experience and 200+ homes built in Charlotte County.',
    eyebrow: 'Our Home Market · Charlotte County',
    h1: 'General Contractor in Port Charlotte, FL',
    lead: 'Port Charlotte is where we have done most of our building for four decades. If you need a general contractor who knows these streets, canals, and block homes, you have found one.',
    facts: [
      ['Population', 'About 60,000 (2020 Census)'],
      ['County', 'Charlotte County (unincorporated)'],
      ['From our office', 'Minutes away — our office is on Pinnacle St, off US-41'],
      ['Permits', 'Charlotte County Community Development'],
    ],
    intro: [
      'Port Charlotte was laid out in the late 1950s by General Development Corporation as one of the largest planned communities in Florida — tens of thousands of platted lots threaded with roughly 165 miles of canals. With around 60,000 residents today, it remains unincorporated, which means building permits run through Charlotte County rather than a city hall. Brunderman Building Co Inc has spent four decades working inside that system, and the majority of the 200-plus homes we have built in Charlotte County stand here.',
      'That history gives us an unusual familiarity with the housing stock. We know the low-slung 1960s and 70s block ranches off Edgewater Drive and Midway Boulevard, with their terrazzo floors and jalousie-era window openings. We know the 1980s and 90s homes around Murdock and the newer construction in Gulf Cove and South Gulf Cove. And we know what Hurricane Charley in 2004 and Hurricane Ian in 2022 did to roofs, soffits, lanais, and interiors across every one of those neighborhoods, because we were building here through both storms.',
      'Whether you are building new on a vacant lot in Section 15 or finally redoing the kitchen in a house you have owned for thirty years, working with a general contractor based right here in Port Charlotte keeps the project simple. Site visits are easy, suppliers are close, and the local permitting process is one we work with every week.',
    ],
    localH2: 'Building and Remodeling on Port Charlotte Lots',
    local: [
      'The typical Port Charlotte lot is about 80 feet wide and 125 feet deep. That standard footprint drives everything: where a three-car garage can fit, how deep a lanai and pool can go before hitting the rear setback, and whether an addition is possible without touching the septic drain field. Large areas of Port Charlotte are still on well and septic, while others have county water and sewer; the difference affects both new construction budgets and what can be added to an existing home.',
      'Canal lots add another layer. Saltwater canals with access to Charlotte Harbor through the Peace and Myakka rivers carry flood-zone designations that set the minimum finished-floor elevation for a new home, and the condition of the seawall matters to the whole project. Freshwater canal lots are generally simpler but still have drainage easements to respect. We evaluate all of this before you settle on a plan.',
    ],
    svc: [
      'New block homes on platted and canal-front lots, engineered for Charlotte County wind and flood requirements.',
      'Whole-house updates for GDC-era ranches — open layouts, impact windows, new floors and ceilings.',
      'Removing pass-throughs and soffits to open 1970s and 80s kitchens to the family room and lanai.',
      'Replacing alcove tubs and shower windows with waterproofed walk-in showers and better storage.',
      'Primary suites, in-law suites, and garage bays designed around 80-by-125-foot lot setbacks and septic fields.',
    ],
    seoH2: 'A Port Charlotte General Contractor Near You',
    seo: [
      'People searching for a general contractor near me in Port Charlotte FL, or for a Port Charlotte building contractor, tend to find a mix of out-of-area companies advertising into the market and a smaller group of builders who genuinely work here every week. Brunderman Building Co Inc is local in the literal sense: our office sits just off US-41 near the Charlotte Harbor bridges, a few minutes from the Port Charlotte Town Center and Charlotte Sports Park. More than 800 customers have hired us, and BuildZoom places us in the top 5% of builders.',
      'Our Port Charlotte work covers the full range — custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions. As a general contractor we coordinate every trade under one contract, handle Charlotte County permitting, and build hurricane-proof homes with impact-rated windows to the Florida Building Code requirements for this wind-borne debris region. Homeowners choose a builder and remodeler with deep roots here because the advice is grounded in what has actually held up in Port Charlotte over forty years.',
    ],
    variantsH3: 'Port Charlotte Neighborhoods We Work In',
    variants: ['Gulf Cove and South Gulf Cove', 'Murdock and the Town Center area', 'Section 15 and the Edgewater Drive corridor', 'Harbour Heights and Charlotte Harbor', 'El Jobean and the Myakka River side', 'Peachland, Midway, and central Port Charlotte'],
    nearbyH3: 'Also Serving the Communities Around Port Charlotte',
    nearby: 'From our <a href="/">Port Charlotte home base</a>, the closest neighboring markets are <a href="/locations/punta-gorda.html">Punta Gorda across the Peace River</a> and <a href="/locations/north-port.html">North Port just over the Sarasota County line</a>. We also cover Deep Creek, Lake Suzy, Rotonda West, and <a href="/locations/charlotte-county.html">the rest of Charlotte County</a> as part of a service area that extends about 50 miles.',
    faqs: [
      ['Who issues building permits in Port Charlotte?', 'Because Port Charlotte is unincorporated, permits are issued by Charlotte County Community Development. We prepare and submit the application, coordinate the required engineering and surveys, and schedule inspections for the work we perform.'],
      ['Is my Port Charlotte lot in a flood zone?', 'Many are, especially near saltwater canals, the harbor, and the rivers. The flood zone and base flood elevation determine the minimum floor height for new construction and can affect how much remodeling is allowed under FEMA\'s 50% rule. We check this at the start of every project.'],
      ['Do you remodel older 1960s and 1970s Port Charlotte homes?', 'Regularly. Those concrete block homes are structurally sound and respond very well to remodeling — opening the kitchen, replacing windows with impact-rated units, updating baths, and adding a proper primary suite are all common projects for us.'],
    ],
  },

  {
    slug: 'punta-gorda',
    city: 'Punta Gorda',
    title: 'Home Builder & Remodeler in Punta Gorda, FL | Brunderman',
    description: 'Punta Gorda home builder and remodeler serving Punta Gorda Isles, Burnt Store Isles & the historic district. Waterfront custom homes and remodeling.',
    eyebrow: 'Charlotte County Seat · Waterfront Building',
    h1: 'Home Builder & Remodeler in Punta Gorda, FL',
    lead: 'From sailboat-access homes in Punta Gorda Isles to cottages on the brick streets downtown, we build and remodel in a city where waterfront rules and historic character both matter.',
    facts: [
      ['Population', 'About 19,500 (2020 Census)'],
      ['County', 'Charlotte County (county seat)'],
      ['From our office', 'Our Pinnacle St office carries a Punta Gorda address'],
      ['Permits', 'City of Punta Gorda Building Division'],
    ],
    intro: [
      'Punta Gorda is small — roughly 19,500 people — but it may be the most varied place we build. On one side of town are Punta Gorda Isles and Burnt Store Isles, deed-restricted canal communities where nearly every home has a dock and a view down a seawalled waterway toward Charlotte Harbor. On the other is one of Southwest Florida\'s oldest downtowns, with tin-roofed cottages, brick-paved streets, and a historic district the city actively protects.',
      'A home builder and remodeler working in Punta Gorda needs to be comfortable in both worlds. In PGI and BSI, the conversation is about flood elevation, seawall setbacks, maximizing the water view, and satisfying the architectural review requirements that many sections carry. In the historic district near Gilchrist Park and Retta Esplanade, it is about respecting original proportions and materials while quietly bringing wiring, plumbing, and wind resistance up to modern standards.',
      'Brunderman Building Co Inc has been part of this community for four decades. Our office address is in Punta Gorda, and after Hurricane Charley made landfall here in 2004 the rebuilding effort reshaped much of the city — including the way homes are now engineered. We carry those lessons into every project.',
    ],
    localH2: 'Waterfront and Historic Homes Need Different Expertise',
    local: [
      'Waterfront lots in Punta Gorda Isles and Burnt Store Isles sit in FEMA flood zones, and new homes must be built with the finished floor at or above the required elevation. That frequently means a stem-wall foundation with compacted fill, carefully planned driveway slopes, and garage floors set lower than living areas where allowed. For remodels of older ground-level PGI homes, FEMA\'s 50% substantial-improvement rule is a central planning issue: exceed the threshold and the entire home must be elevated or otherwise brought into compliance. We help owners scope and phase projects with that limit clearly in view.',
      'In the downtown historic district, exterior changes are subject to city review, and the right approach is usually restoration-minded: repairing rather than replacing where possible, matching siding profiles and window proportions, and keeping additions subordinate to the original structure. Inland neighborhoods such as Burnt Store Meadows and Deep Creek are more conventional, and well suited to straightforward custom homes and remodeling.',
    ],
    svc: [
      'Waterfront custom homes in PGI and BSI, elevated to flood requirements and oriented to the canal view.',
      'Renovations planned around the FEMA 50% rule for older ground-level canal homes.',
      'Kitchens reoriented so the island and sink look out over the pool and the water.',
      'Spa-style primary baths and accessible showers for owners planning to stay long term.',
      'Additions and enclosed lanais that respect seawall setbacks and community deed restrictions.',
    ],
    seoH2: 'A Punta Gorda Builder and Remodeling Contractor Near You',
    seo: [
      'If you are comparing custom home builders in Punta Gorda FL, or searching for a remodeling contractor near me for a home in the Isles, look closely at waterfront experience. Building beside a seawall is not the same as building inland. Soil conditions, elevation, corrosion-resistant fasteners and hardware, impact-rated windows facing open water, and dock and lift coordination all come into play. Brunderman Building Co Inc has four decades of experience with exactly these conditions, a top 5% builder rating from BuildZoom, and more than 800 customers behind us.',
      'We offer the same core services in Punta Gorda that we do across Charlotte County: custom home construction, whole-home remodeling, kitchen remodeling, bathroom remodeling, and home additions. The City of Punta Gorda runs its own building division, separate from the county, and we are accustomed to its submittal and inspection process. One reviewer called us "the most experienced builders in the area" — in a city with this many specialized requirements, that experience is the point.',
    ],
    variantsH3: 'Where We Work in Punta Gorda',
    variants: ['Punta Gorda Isles (PGI)', 'Burnt Store Isles (BSI)', 'Downtown historic district', 'Burnt Store Meadows', 'Deep Creek', 'Burnt Store Road corridor and Burnt Store Marina area'],
    nearbyH3: 'Nearby Service Areas',
    nearby: 'Punta Gorda is at the center of our territory. Across the US-41 bridges is <a href="/locations/port-charlotte.html">Port Charlotte, where most of our homes have been built</a>, and the rest of <a href="/locations/charlotte-county.html">Charlotte County</a> — Burnt Store, Deep Creek, Harbour Heights, and Babcock Ranch to the east — is a short drive away. See the <a href="/">Brunderman Building Co Inc homepage</a> for the full service area.',
    faqs: [
      ['Do you build in Punta Gorda Isles and Burnt Store Isles?', 'Yes. We build new waterfront homes and remodel existing ones in both communities, and we work within the deed restrictions and architectural review requirements that apply to many sections.'],
      ['My PGI home is at ground level. How much remodeling can I do?', 'If the home is below the current required flood elevation, improvements are limited by FEMA\'s 50% rule as administered by the City of Punta Gorda. The limit is based on the value of the structure, not the land. We help you understand the numbers before designing the project.'],
      ['Can you work on a home in the historic district?', 'We can. Exterior work in the district typically requires city review, and we plan projects to be compatible with the home\'s original character while improving its structure, systems, and storm resistance.'],
    ],
  },

  {
    slug: 'north-port',
    city: 'North Port',
    title: 'Home Builder & Remodeler in North Port, FL | Brunderman',
    description: 'North Port, FL home builder and remodeler. Build on your lot, remodel a kitchen or bath, or add on — four decades of Southwest Florida experience.',
    eyebrow: 'Sarasota County · Build On Your Lot',
    h1: 'Home Builder & Remodeler in North Port, FL',
    lead: 'North Port has more buildable lots than almost anywhere in the region. We help owners turn them into custom homes — and help longtime residents remodel the houses they already have.',
    facts: [
      ['Population', 'About 75,000 (2020 Census) and growing fast'],
      ['County', 'Sarasota County'],
      ['From our office', 'Roughly 10–15 miles north via US-41 or I-75'],
      ['Permits', 'City of North Port Building Division'],
    ],
    intro: [
      'By land area, North Port is one of the largest cities in Florida, and for years much of it was empty: thousands of platted lots along quiet streets off Toledo Blade, Sumter, and Price boulevards, waiting for someone to build. That has changed quickly. The 2020 Census counted about 75,000 residents, and the number has climbed every year since, making North Port one of the fastest-growing cities in the state.',
      'For a custom home builder, North Port is a build-on-your-lot market. Many of our clients here bought a lot years ago — or inherited one — and are now ready to build. Others are relocating and have discovered that a vacant lot plus a custom home can compare well with buying in one of the master-planned communities out in Wellen Park. Either way, the process starts with understanding the lot, and that is where an experienced home builder and remodeler earns its keep.',
      'We are just down the road. Brunderman Building Co Inc is based a short drive south in Charlotte County, where we have built more than 200 homes over four decades. North Port and Port Charlotte were platted by the same developer, with the same lot dimensions and much the same soil and drainage, so the work is second nature.',
    ],
    localH2: 'What to Know Before Building in North Port',
    local: [
      'Most undeveloped North Port lots rely on a private well and a septic system, because city water and sewer reach only part of the platted area. The septic system type is determined by soil and water-table conditions, and the required drain field can take up a meaningful part of the lot — which affects where the house, driveway, and any future pool can go. Lots also need to be checked for protected species: gopher tortoise burrows and scrub-jay habitat both occur here and must be addressed through the proper process before clearing.',
      'None of this is a reason not to build; it simply needs to be budgeted and scheduled. We walk North Port owners through lot clearing, fill, well and septic, culvert and driveway requirements, and city impact fees up front, so the price of the home reflects the real cost of building on that particular piece of ground. For established neighborhoods like Heron Creek, Bobcat Trail, and Sabal Trace, the conversation shifts to remodeling homes from the 1990s and 2000s that are due for new kitchens, baths, and flooring.',
    ],
    svc: [
      'Build-on-your-lot custom homes, including clearing, fill, well, septic, and driveway site work.',
      'Interior renovations for 1990s–2000s homes in established golf and lake communities.',
      'Builder-grade kitchens replaced with real cabinetry, quartz, and an island that fits how you cook.',
      'Garden tubs removed in favor of large tiled walk-in showers and double vanities.',
      'Extra bedrooms, offices, and garage space, sited clear of the well and septic drain field.',
    ],
    seoH2: 'North Port Home Builders and Remodelers Near You',
    seo: [
      'Search for home builders near me in North Port FL and you will see large regional production builders alongside local custom builders. The production companies are efficient at building their own plans in their own communities. If you want a specific plan on your own lot — or you want to change the plan — a custom builder is the better fit. Brunderman Building Co Inc builds hurricane-proof homes with impact-rated windows one at a time for the person who will live in it, backed by four decades of experience, a top 5% BuildZoom rating, and the trust of more than 800 customers.',
      'Our North Port services include custom home construction, home remodeling, kitchen remodeling, bathroom remodeling, and home additions. The City of North Port operates its own building department, and we handle the permit submittals, engineering coordination, and inspections. After Hurricane Ian flooded parts of North Port in 2022, particularly near the Myakkahatchee Creek, many homeowners also needed a remodeling contractor for interior rebuilds — work we know well and continue to perform.',
    ],
    variantsH3: 'North Port Projects We Commonly See',
    variants: ['Custom homes on platted lots off Toledo Blade and Price boulevards', 'Well, septic, and site work packages for vacant lots', 'Kitchen and bath remodeling in Heron Creek and Bobcat Trail', 'Post-storm interior rebuilds and flooring replacement', 'Garage additions and workshop space on oversized lots', 'Remodels near Warm Mineral Springs and North Port Estates acreage'],
    nearbyH3: 'Neighboring Areas We Serve',
    nearby: 'North Port sits between two of our other markets: <a href="/locations/port-charlotte.html">Port Charlotte to the south</a>, which shares the same platted-lot layout, and <a href="/locations/venice.html">the Venice area to the northwest</a> along US-41 and I-75. Learn more about our company on the <a href="/">main Brunderman Building Co Inc page</a>.',
    faqs: [
      ['I own a vacant lot in North Port. Can you build on it?', 'Very likely. We start with a lot evaluation covering flood zone, fill requirements, well and septic feasibility, protected species, and access. Once we know what the lot requires, we can price the site work together with the home.'],
      ['Will my North Port lot need a well and septic system?', 'Many do. City utilities serve only portions of North Port. If water and sewer are not available at your lot, a private well and an approved septic system are part of the build, and we coordinate both.'],
      ['Do you work in Wellen Park?', 'Most new homes in Wellen Park are built by the community\'s designated builders. We are available there for remodeling and improvement work on existing homes, subject to the community\'s rules for outside contractors.'],
    ],
  },

  {
    slug: 'venice',
    city: 'Venice',
    title: 'Home Builder & Remodeler in Venice, FL | Brunderman Building',
    description: 'Venice, FL home builder and remodeler. Remodeling for island homes, South Venice & Venice Gardens, plus custom homes and additions. 4 decades of experience.',
    eyebrow: 'Sarasota County · Gulf Coast',
    h1: 'Home Builder & Remodeler in Venice, FL',
    lead: 'Venice was planned as a showpiece city in the 1920s, and it still takes its architecture seriously. We remodel and build here with that character — and the Gulf weather — in mind.',
    facts: [
      ['Population', 'About 25,500 (2020 Census)'],
      ['County', 'Sarasota County'],
      ['From our office', 'Roughly 30 miles northwest via I-75 or US-41'],
      ['Permits', 'City of Venice or Sarasota County, depending on address'],
    ],
    intro: [
      'Few Florida towns have a pedigree like Venice. The city\'s layout was drawn in 1926 by John Nolen, one of the country\'s pioneering urban planners, with broad boulevards, parks, and a Northern Italian architectural theme that still defines West Venice Avenue and the historic neighborhoods on the island. About 25,500 people live within the city limits, and a good many more in the unincorporated areas around it — South Venice, Venice Gardens, Nokomis, and the newer communities east of I-75 along Jacaranda Boulevard.',
      'For a home builder and remodeler, that mix produces very different projects within a few miles of each other. On the island, we are often asked to update a mid-century or Mediterranean Revival home without losing what makes it charming: barrel-tile roofs, arched openings, stucco detailing. In South Venice and Venice Gardens, the work is practical remodeling of 1960s–80s block homes on modest lots. Out east, it is kitchens, baths, and additions in 1990s and 2000s subdivisions.',
      'Venice is at the northern end of Brunderman Building Co Inc\'s 50-mile service radius, about half an hour up I-75 from our Charlotte County base. We take on projects here selectively and staff them properly, bringing the same four decades of experience that built more than 200 homes to the south.',
    ],
    localH2: 'Remodeling Around Venice\'s Architecture and Review Process',
    local: [
      'Parts of the City of Venice fall within historic and architectural control districts where exterior changes — windows, doors, roofing, additions, even colors in some cases — go before the city\'s review board. Approval is very achievable when the design respects the district\'s Northern Italian and Mediterranean vocabulary, and we plan submittals accordingly. Replacing original windows with impact-rated units that keep the right proportions and muntin patterns is a typical example of balancing preservation with storm protection.',
      'Outside the city limits, Sarasota County handles permitting, and the concerns are more familiar: flood zones near the Intracoastal Waterway, Roberts Bay, and the Myakka River; septic systems in South Venice; and homeowner association approvals in the gated communities. Knowing at the outset whether an address is city or county saves time, and we confirm it before any design work begins.',
    ],
    svc: [
      'Custom homes on infill and teardown lots, designed to fit established Venice streetscapes.',
      'Character-sensitive renovations on the island and practical updates in South Venice and Venice Gardens.',
      'Kitchen renovations that open compact mid-century layouts while keeping period charm.',
      'Bathroom remodeling with accessible showers for Venice\'s many long-term and retired residents.',
      'Primary suites, Florida rooms, and garage additions reviewed against city or county setbacks.',
    ],
    seoH2: 'Venice Remodeling Contractor and Home Builder Near You',
    seo: [
      'Anyone looking up a remodeling contractor near me in Venice FL will find no shortage of options, so it is fair to ask why a Charlotte County builder is worth a call. The answer is depth of experience. Brunderman Building Co Inc has spent four decades building and remodeling concrete block homes in the same climate, under the same Florida Building Code, a few exits down the interstate. We are rated in the top 5% of builders on BuildZoom, more than 800 customers have hired us, and our reviewers consistently mention professionalism, punctuality, and quality.',
      'In Venice we provide home remodeling, kitchen remodeling, bathroom remodeling, home additions, and custom home construction. Because so much of the local housing dates from the 1950s through the 1980s, remodeling is the most common request: replacing original kitchens and baths, swapping jalousie and single-pane windows for impact-rated windows, removing walls to open the living area, and upgrading electrical service for modern loads. We handle the design coordination, the permits with the City of Venice or Sarasota County, and every trade involved.',
    ],
    variantsH3: 'Venice-Area Neighborhoods',
    variants: ['Venice Island and the historic districts', 'South Venice', 'Venice Gardens', 'Nokomis and Laurel', 'Jacaranda Boulevard and east-of-I-75 communities', 'Golden Beach and the Venice Avenue corridor'],
    nearbyH3: 'Areas Near Venice We Also Cover',
    nearby: 'South of Venice, our work continues into <a href="/locations/north-port.html">North Port and the Wellen Park area</a> and down through Englewood and Rotonda West into <a href="/locations/charlotte-county.html">Charlotte County</a>, where most of our homes have been built. For an overview of the company, visit the <a href="/">Brunderman Building Co Inc homepage</a>.',
    faqs: [
      ['Do you travel to Venice from Port Charlotte?', 'Yes. Venice is within our 50-mile service area, about a half-hour drive up I-75. We schedule Venice projects so crews and supervision are on site consistently, just as they would be closer to home.'],
      ['My home is in a Venice historic district. Can I replace the windows?', 'Generally yes, with approval. The city\'s review process looks at whether new windows are compatible with the home\'s architecture. We select impact-rated products with appropriate proportions and prepare the submittal.'],
      ['Is my address in the City of Venice or unincorporated Sarasota County?', 'Many "Venice" mailing addresses — including South Venice and Venice Gardens — are actually in unincorporated Sarasota County. We verify the jurisdiction at the start because it determines where permits are filed and which zoning rules apply.'],
    ],
  },
];
